//! Streaming response handling for the Cohere API.

use serde::{Deserialize, Serialize};

use crate::types::{ApiMeta, Document, FinishReason};

#[cfg(feature = "chat")]
use crate::chat::{Citation, ToolCall};

/// A stream event from the Cohere API.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "event_type", rename_all = "snake_case")]
pub enum StreamEvent {
    /// The streaming has started.
    StreamStart {
        /// Generation ID.
        #[serde(rename = "generation_id")]
        generation_id: String,
    },

    /// Text generation event.
    TextGeneration {
        /// The generated text.
        text: String,
    },

    /// Search queries generated by the model.
    SearchQueriesGeneration {
        /// The search queries.
        #[serde(rename = "search_queries")]
        search_queries: Vec<SearchQuery>,
    },

    /// Search results event.
    SearchResults {
        /// The search results/documents.
        #[serde(rename = "search_results")]
        search_results: Option<Vec<Document>>,
        /// The documents used.
        documents: Option<Vec<Document>>,
    },

    /// Tool calls planned by the model.
    ToolCallsGeneration {
        /// The tool calls.
        #[serde(rename = "tool_calls")]
        tool_calls: Vec<ToolCall>,
    },

    /// Tool calls chunk (for streaming tool calls).
    ToolCallsChunk {
        /// The tool call information.
        #[serde(rename = "tool_call_delta")]
        tool_call_delta: ToolCallDelta,
    },

    /// Citation event.
    Citation {
        /// The citation information.
        citation: Citation,
    },

    /// Response generation is ending.
    StreamEnd {
        /// The finish reason.
        #[serde(rename = "finish_reason")]
        finish_reason: FinishReason,
        /// Generation ID.
        #[serde(rename = "generation_id")]
        generation_id: String,
        /// Response text.
        #[serde(rename = "response")]
        response: Option<StreamEndResponse>,
        /// Additional metadata.
        #[serde(skip_serializing_if = "Option::is_none")]
        meta: Option<ApiMeta>,
    },
}

/// Search query from the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchQuery {
    /// The search query text.
    pub text: String,
    /// Optional connector to use for search.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connector: Option<String>,
}

/// Tool call delta for streaming.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallDelta {
    /// The tool call information.
    #[serde(rename = "tool_call")]
    pub tool_call: ToolCall,
}

/// Response at stream end.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamEndResponse {
    /// The response text.
    pub text: String,
    /// Additional metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<ApiMeta>,
}

/// Result type for streaming operations.
pub type StreamResult<T> = std::result::Result<T, crate::error::CohereError>;

/// A collector that accumulates streaming events into a complete response.
#[derive(Debug, Default)]
pub struct StreamCollector {
    generation_id: Option<String>,
    text: String,
    tool_calls: Vec<ToolCall>,
    citations: Vec<Citation>,
    search_queries: Vec<SearchQuery>,
    finish_reason: Option<FinishReason>,
    meta: Option<ApiMeta>,
}

impl StreamCollector {
    /// Create a new stream collector.
    pub fn new() -> Self {
        Self::default()
    }

    /// Process a stream event.
    pub fn process_event(&mut self, event: &StreamEvent) {
        match event {
            StreamEvent::StreamStart { generation_id } => {
                self.generation_id = Some(generation_id.clone());
            }
            StreamEvent::TextGeneration { text } => {
                self.text.push_str(text);
            }
            StreamEvent::ToolCallsGeneration { tool_calls } => {
                self.tool_calls.extend(tool_calls.clone());
            }
            StreamEvent::ToolCallsChunk { tool_call_delta } => {
                self.tool_calls.push(tool_call_delta.tool_call.clone());
            }
            StreamEvent::Citation { citation } => {
                self.citations.push(citation.clone());
            }
            StreamEvent::SearchQueriesGeneration { search_queries } => {
                self.search_queries.extend(search_queries.clone());
            }
            StreamEvent::StreamEnd {
                finish_reason,
                meta,
                ..
            } => {
                self.finish_reason = Some(*finish_reason);
                self.meta = meta.clone();
            }
            _ => {}
        }
    }

    /// Get the collected text so far.
    pub fn current_text(&self) -> &str {
        &self.text
    }

    /// Get the generation ID if available.
    pub fn generation_id(&self) -> Option<&str> {
        self.generation_id.as_deref()
    }

    /// Get the finish reason if available.
    pub fn finish_reason(&self) -> Option<FinishReason> {
        self.finish_reason
    }

    /// Get the collected tool calls.
    pub fn tool_calls(&self) -> &[ToolCall] {
        &self.tool_calls
    }

    /// Get the collected citations.
    pub fn citations(&self) -> &[Citation] {
        &self.citations
    }

    /// Get the metadata if available.
    pub fn meta(&self) -> Option<&ApiMeta> {
        self.meta.as_ref()
    }

    /// Check if the stream has finished.
    pub fn is_complete(&self) -> bool {
        self.finish_reason.is_some()
    }

    /// Build the final response text.
    pub fn build_text(&self) -> Option<String> {
        if self.text.is_empty() {
            None
        } else {
            Some(self.text.clone())
        }
    }
}

/// Helper function to collect all events from a stream.
pub async fn collect_stream<S>(mut stream: S) -> (Vec<StreamEvent>, StreamCollector)
where
    S: futures::Stream<Item = StreamResult<StreamEvent>> + Unpin,
{
    use futures::StreamExt;

    let mut events = Vec::new();
    let mut collector = StreamCollector::new();

    while let Some(result) = stream.next().await {
        if let Ok(event) = result {
            collector.process_event(&event);
            events.push(event);
        }
    }

    (events, collector)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stream_collector() {
        let mut collector = StreamCollector::new();

        // Simulate streaming events
        let start = StreamEvent::StreamStart {
            generation_id: "gen_123".to_string(),
        };
        collector.process_event(&start);

        let text1 = StreamEvent::TextGeneration {
            text: "Hello".to_string(),
        };
        collector.process_event(&text1);

        let text2 = StreamEvent::TextGeneration {
            text: " world!".to_string(),
        };
        collector.process_event(&text2);

        assert_eq!(collector.current_text(), "Hello world!");
        assert_eq!(collector.generation_id(), Some("gen_123"));
    }

    #[test]
    fn test_search_query() {
        let query = SearchQuery {
            text: "what is rust".to_string(),
            connector: Some("web-search".to_string()),
        };

        assert_eq!(query.text, "what is rust");
        assert_eq!(query.connector, Some("web-search".to_string()));
    }
}
