pub mod channels;
pub mod chat;
pub mod control;
#[cfg(feature = "cursor")]
pub mod cursor;
pub mod doctor;
pub mod mcp2cli;
pub mod meet;
pub mod matrix;
pub mod memory;
pub mod models;
pub mod onboard;
pub mod optimize;
pub mod schedule;
pub mod security;
pub mod session;
pub mod signal;
pub mod skills;
pub mod start;
#[cfg(feature = "voice")]
pub mod talk;
pub mod webhooks;
