pub mod chat;
#[cfg(feature = "cursor")]
pub mod cursor;
pub mod doctor;
pub mod memory;
pub mod mcp2cli;
pub mod models;
pub mod onboard;
pub mod schedule;
pub mod security;
pub mod skills;
pub mod start;
#[cfg(feature = "voice")]
pub mod talk;
pub mod webhooks;
