# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13orchestration.proto\x12\x1aopenrustclaw.orchestration\"\xc6\x01\n\x0fWorkflowRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\t\x12K\n\x08metadata\x18\x04 \x03(\x0b\x32\x39.openrustclaw.orchestration.WorkflowRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"f\n\x10WorkflowResponse\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\"U\n\x0eWorkflowUpdate\x12\x11\n\tstep_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\"\"\n\rStatusRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\"O\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_step\x18\x02 \x01(\t\x12\x17\n\x0fsteps_completed\x18\x03 \x01(\x05\x32\xe4\x02\n\x14OrchestrationService\x12l\n\x0f\x45xecuteWorkflow\x12+.openrustclaw.orchestration.WorkflowRequest\x1a,.openrustclaw.orchestration.WorkflowResponse\x12r\n\x15\x45xecuteWorkflowStream\x12+.openrustclaw.orchestration.WorkflowRequest\x1a*.openrustclaw.orchestration.WorkflowUpdate0\x01\x12j\n\x11GetWorkflowStatus\x12).openrustclaw.orchestration.StatusRequest\x1a*.openrustclaw.orchestration.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKFLOWREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_WORKFLOWREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_WORKFLOWREQUEST']._serialized_start=52
  _globals['_WORKFLOWREQUEST']._serialized_end=250
  _globals['_WORKFLOWREQUEST_METADATAENTRY']._serialized_start=203
  _globals['_WORKFLOWREQUEST_METADATAENTRY']._serialized_end=250
  _globals['_WORKFLOWRESPONSE']._serialized_start=252
  _globals['_WORKFLOWRESPONSE']._serialized_end=354
  _globals['_WORKFLOWUPDATE']._serialized_start=356
  _globals['_WORKFLOWUPDATE']._serialized_end=441
  _globals['_STATUSREQUEST']._serialized_start=443
  _globals['_STATUSREQUEST']._serialized_end=477
  _globals['_STATUSRESPONSE']._serialized_start=479
  _globals['_STATUSRESPONSE']._serialized_end=558
  _globals['_ORCHESTRATIONSERVICE']._serialized_start=561
  _globals['_ORCHESTRATIONSERVICE']._serialized_end=917
# @@protoc_insertion_point(module_scope)
