# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import orchestration_pb2 as orchestration__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestrationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkflow = channel.unary_unary(
                '/openrustclaw.orchestration.OrchestrationService/ExecuteWorkflow',
                request_serializer=orchestration__pb2.WorkflowRequest.SerializeToString,
                response_deserializer=orchestration__pb2.WorkflowResponse.FromString,
                _registered_method=True)
        self.ExecuteWorkflowStream = channel.unary_stream(
                '/openrustclaw.orchestration.OrchestrationService/ExecuteWorkflowStream',
                request_serializer=orchestration__pb2.WorkflowRequest.SerializeToString,
                response_deserializer=orchestration__pb2.WorkflowUpdate.FromString,
                _registered_method=True)
        self.GetWorkflowStatus = channel.unary_unary(
                '/openrustclaw.orchestration.OrchestrationService/GetWorkflowStatus',
                request_serializer=orchestration__pb2.StatusRequest.SerializeToString,
                response_deserializer=orchestration__pb2.StatusResponse.FromString,
                _registered_method=True)


class OrchestrationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteWorkflow(self, request, context):
        """Execute a LangGraph workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWorkflowStream(self, request, context):
        """Execute a workflow with streaming updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowStatus(self, request, context):
        """Check workflow status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkflow,
                    request_deserializer=orchestration__pb2.WorkflowRequest.FromString,
                    response_serializer=orchestration__pb2.WorkflowResponse.SerializeToString,
            ),
            'ExecuteWorkflowStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteWorkflowStream,
                    request_deserializer=orchestration__pb2.WorkflowRequest.FromString,
                    response_serializer=orchestration__pb2.WorkflowUpdate.SerializeToString,
            ),
            'GetWorkflowStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowStatus,
                    request_deserializer=orchestration__pb2.StatusRequest.FromString,
                    response_serializer=orchestration__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openrustclaw.orchestration.OrchestrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openrustclaw.orchestration.OrchestrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestrationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openrustclaw.orchestration.OrchestrationService/ExecuteWorkflow',
            orchestration__pb2.WorkflowRequest.SerializeToString,
            orchestration__pb2.WorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteWorkflowStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openrustclaw.orchestration.OrchestrationService/ExecuteWorkflowStream',
            orchestration__pb2.WorkflowRequest.SerializeToString,
            orchestration__pb2.WorkflowUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openrustclaw.orchestration.OrchestrationService/GetWorkflowStatus',
            orchestration__pb2.StatusRequest.SerializeToString,
            orchestration__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
